### ISSUE TITLE
Incompatible Rz Implementation 

### ISSUE THREAD

**Issue by YunJ1e** [Agony5757/QPanda-lite#38]
https://github.com/Agony5757/QPanda-lite/blob/b47d14d295d68f51772a7922e60c981aad5b3a59/QPandaLiteCpp/src/simulator.cpp#L354C26-L354C26

The desired matrix form of RZ is supposed to be,

$$
\begin{bmatrix}
\exp(-i\theta/2) & 0 \\
0 & \exp(i\theta/2)
\end{bmatrix}.
$$

But the current implementation is,

$$
\begin{bmatrix}
1 & 0 \\
0 & \exp(i\theta)
\end{bmatrix}.
$$

Although there is only a global phase for the single-qubit case, there will be issues if we add control to it due to the extra phase.

**Comment by Agony5757** [comment]
Solved
