### ISSUE TITLE
[bug] submit task with dummy config without data cache writing

### ISSUE THREAD

**Issue by RichardSun2019** [Agony5757/QPanda-lite#40]
https://github.com/Agony5757/QPanda-lite/blob/3b830b8afffc7d553be22f167d836acbd470b430/qpandalite/task/originq_dummy/task.py#L233C17-L242C60

When `auto_mapping` is true, the `results` will be lost. The referred code should be unindented.

**Comment by Agony5757** [comment]
Solved
